metrics_list = ['braycurtis', 
                'canberra', 
                'euclidean' 
                # 'cdist',
                # 'chebyshev',
                # 'cityblock',
                # 'correlation',
                # 'cosine',
                # 'dice',
                # 'directed_hausdorff',
                # 'hamming',
                # 'is_valid_dm',
                # 'is_valid_y',
                # 'jaccard',
                # 'jensenshannon',
                # 'mahalanobis',
                # 'minkowski',
                # 'num_obs_dm',
                # 'num_obs_y',
                # 'pdist',
                # 'rogerstanimoto',
                # 'russellrao',
                # 'seuclidean',
                # 'sokalsneath',
                # 'sqeuclidean',
                # 'squareform',
                # 'yule'
                ]